package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"

	"github.com/ihavespoons/tau/ai"
)

// emitAll writes one generated file per provider.
func emitAll(outDir string, catalogs map[string][]ai.Model) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	// Stale catalogs are removed first: a provider that disappears upstream
	// must not linger as a file nobody regenerates.
	existing, _ := filepath.Glob(filepath.Join(outDir, "zz_generated_*.go"))
	keep := map[string]bool{}
	for id := range catalogs {
		keep[filepath.Join(outDir, "zz_generated_"+id+".go")] = true
	}
	for _, path := range existing {
		if !keep[path] {
			if err := os.Remove(path); err != nil {
				return err
			}
		}
	}

	ids := make([]string, 0, len(catalogs))
	for id := range catalogs {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	for _, id := range ids {
		src, err := renderCatalog(id, catalogs[id])
		if err != nil {
			return fmt.Errorf("rendering %s: %w", id, err)
		}
		path := filepath.Join(outDir, "zz_generated_"+id+".go")
		if err := os.WriteFile(path, src, 0o644); err != nil {
			return err
		}
	}

	index, err := renderIndex(ids)
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(outDir, "zz_generated_index.go"), index, 0o644)
}

const header = "// Code generated by cmd/tau-genmodels. DO NOT EDIT.\n\npackage catalog\n\nimport \"github.com/ihavespoons/tau/ai\"\n\n"

func renderCatalog(providerID string, models []ai.Model) ([]byte, error) {
	var b strings.Builder
	b.WriteString(header)
	fmt.Fprintf(&b, "// %s is the compiled model catalog for %q.\nvar %s = []ai.Model{\n",
		goIdent(providerID), providerID, goIdent(providerID))
	for i := range models {
		b.WriteString(renderModel(&models[i]))
	}
	b.WriteString("}\n")
	return format.Source([]byte(b.String()))
}

func renderIndex(ids []string) ([]byte, error) {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("// Catalogs maps a provider id to its compiled models.\n")
	b.WriteString("//\n")
	b.WriteString("// It is the generator's index: every provider tau knows about without\n")
	b.WriteString("// configuration appears here, and nothing else does.\n")
	b.WriteString("var Catalogs = map[string][]ai.Model{\n")
	for _, id := range ids {
		fmt.Fprintf(&b, "\t%q: %s,\n", id, goIdent(id))
	}
	b.WriteString("}\n")
	return format.Source([]byte(b.String()))
}

// renderModel writes one composite literal. Fields at their zero value are
// omitted, which is what keeps a 1000-model catalog readable enough to review
// in a diff.
func renderModel(m *ai.Model) string {
	var b strings.Builder
	b.WriteString("\t{\n")
	fmt.Fprintf(&b, "\t\tID: %q, Name: %q,\n", m.ID, m.Name)
	fmt.Fprintf(&b, "\t\tApi: %s, Provider: %q, BaseURL: %q,\n", apiConst(m.Api), string(m.Provider), m.BaseURL)
	if m.Reasoning {
		b.WriteString("\t\tReasoning: true,\n")
	}
	if len(m.ThinkingLevelMap) > 0 {
		fmt.Fprintf(&b, "\t\tThinkingLevelMap: %s,\n", renderThinkingMap(m.ThinkingLevelMap))
	}
	fmt.Fprintf(&b, "\t\tInput: %s,\n", renderStrings(m.Input))
	fmt.Fprintf(&b, "\t\tCost: %s,\n", renderCost(m.Cost))
	fmt.Fprintf(&b, "\t\tContextWindow: %d, MaxTokens: %d,\n", m.ContextWindow, m.MaxTokens)
	if len(m.Headers) > 0 {
		fmt.Fprintf(&b, "\t\tHeaders: %s,\n", renderHeaders(m.Headers))
	}
	if m.Compat != nil {
		if flags := renderCompat(m.Compat); flags != "" {
			fmt.Fprintf(&b, "\t\tCompat: %s,\n", flags)
		}
	}
	b.WriteString("\t},\n")
	return b.String()
}

func apiConst(api ai.Api) string {
	switch api {
	case ai.ApiOpenAICompletions:
		return "ai.ApiOpenAICompletions"
	case ai.ApiMistralConversations:
		return "ai.ApiMistralConversations"
	case ai.ApiOpenAIResponses:
		return "ai.ApiOpenAIResponses"
	case ai.ApiAzureOpenAIResponses:
		return "ai.ApiAzureOpenAIResponses"
	case ai.ApiOpenAICodexResponses:
		return "ai.ApiOpenAICodexResponses"
	case ai.ApiAnthropicMessages:
		return "ai.ApiAnthropicMessages"
	case ai.ApiBedrockConverse:
		return "ai.ApiBedrockConverse"
	case ai.ApiGoogleGenerativeAI:
		return "ai.ApiGoogleGenerativeAI"
	case ai.ApiGoogleVertex:
		return "ai.ApiGoogleVertex"
	case ai.ApiPiMessages:
		return "ai.ApiPiMessages"
	default:
		return strconv.Quote(string(api))
	}
}

func renderStrings(ss []string) string {
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = strconv.Quote(s)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func renderHeaders(h map[string]string) string {
	keys := make([]string, 0, len(h))
	for k := range h {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	parts := make([]string, len(keys))
	for i, k := range keys {
		parts[i] = fmt.Sprintf("%q: %q", k, h[k])
	}
	return "map[string]string{" + strings.Join(parts, ", ") + "}"
}

// renderThinkingMap keeps a nil value as an explicit nil: it means the level is
// unsupported, which is not the same as the level being absent.
func renderThinkingMap(m ai.ThinkingLevelMap) string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, string(k))
	}
	sort.Strings(keys)

	parts := make([]string, 0, len(keys))
	for _, k := range keys {
		v := m[ai.ModelThinkingLevel(k)]
		if v == nil {
			parts = append(parts, fmt.Sprintf("%q: nil", k))
			continue
		}
		parts = append(parts, fmt.Sprintf("%q: strptr(%q)", k, *v))
	}
	return "ai.ThinkingLevelMap{" + strings.Join(parts, ", ") + "}"
}

func renderCost(c ai.ModelCost) string {
	rates := renderRates(c.ModelCostRates)
	if len(c.Tiers) == 0 {
		return "ai.ModelCost{ModelCostRates: " + rates + "}"
	}
	var tiers []string
	for _, t := range c.Tiers {
		tiers = append(tiers, fmt.Sprintf("{InputTokensAbove: %d, ModelCostRates: %s}",
			t.InputTokensAbove, renderRates(t.ModelCostRates)))
	}
	return "ai.ModelCost{ModelCostRates: " + rates +
		", Tiers: []ai.ModelCostTier{" + strings.Join(tiers, ", ") + "}}"
}

func renderRates(r ai.ModelCostRates) string {
	var parts []string
	add := func(name string, v float64) {
		if v != 0 {
			parts = append(parts, fmt.Sprintf("%s: %s", name, formatFloat(v)))
		}
	}
	add("Input", r.Input)
	add("Output", r.Output)
	add("CacheRead", r.CacheRead)
	add("CacheWrite", r.CacheWrite)
	return "ai.ModelCostRates{" + strings.Join(parts, ", ") + "}"
}

// formatFloat writes the shortest representation that round-trips, so prices
// stay recognisable (3 rather than 3.0000000000000004).
func formatFloat(f float64) string {
	s := strconv.FormatFloat(f, 'g', -1, 64)
	if !strings.ContainsAny(s, ".eE") {
		return s
	}
	return s
}

// renderCompat writes only the flags that are set. It reflects over the struct
// so a new compat flag needs no change here — forgetting to add a case would
// silently drop the flag from every generated catalog.
func renderCompat(c *ai.CompatFlags) string {
	v := reflect.ValueOf(*c)
	t := v.Type()

	var parts []string
	for i := 0; i < t.NumField(); i++ {
		fv := v.Field(i)
		if fv.Kind() == reflect.Pointer && fv.IsNil() {
			continue
		}
		if fv.Kind() != reflect.Pointer && fv.IsZero() {
			continue
		}
		rendered, ok := renderCompatValue(fv)
		if !ok {
			continue
		}
		parts = append(parts, t.Field(i).Name+": "+rendered)
	}
	if len(parts) == 0 {
		return ""
	}
	return "&ai.CompatFlags{" + strings.Join(parts, ", ") + "}"
}

func renderCompatValue(fv reflect.Value) (string, bool) {
	if fv.Kind() == reflect.Pointer {
		elem := fv.Elem()
		switch elem.Kind() {
		case reflect.Bool:
			return fmt.Sprintf("boolptr(%t)", elem.Bool()), true
		case reflect.String:
			return fmt.Sprintf("strptr(%q)", elem.String()), true
		case reflect.Int, reflect.Int64:
			return fmt.Sprintf("intptr(%d)", elem.Int()), true
		}
		return "", false
	}
	if fv.Kind() == reflect.Map && fv.Type().Key().Kind() == reflect.String {
		return renderAnyMap(fv), true
	}
	return "", false
}

func renderAnyMap(fv reflect.Value) string {
	keys := make([]string, 0, fv.Len())
	for _, k := range fv.MapKeys() {
		keys = append(keys, k.String())
	}
	sort.Strings(keys)

	parts := make([]string, 0, len(keys))
	for _, k := range keys {
		val := fv.MapIndex(reflect.ValueOf(k)).Interface()
		parts = append(parts, fmt.Sprintf("%q: %#v", k, val))
	}
	return fv.Type().String() + "{" + strings.Join(parts, ", ") + "}"
}
