// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// Catalogs maps a provider id to its compiled models.
//
// It is the generator's index: every provider tau knows about without
// configuration appears here, and nothing else does.
var Catalogs = map[string][]ai.Model{
	"anthropic":             AnthropicModels,
	"cerebras":              CerebrasModels,
	"cloudflare-workers-ai": CloudflareWorkersAIModels,
	"google":                GoogleModels,
	"groq":                  GroqModels,
	"huggingface":           HuggingfaceModels,
	"mistral":               MistralModels,
	"moonshotai":            MoonshotaiModels,
	"moonshotai-cn":         MoonshotaiCNModels,
	"openai":                OpenaiModels,
	"openrouter":            OpenrouterModels,
	"vercel-ai-gateway":     VercelAIGatewayModels,
	"xai":                   XaiModels,
	"xiaomi":                XiaomiModels,
}
