// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// Catalogs maps a provider id to its compiled models.
//
// It is the generator's index: every provider tau knows about without
// configuration appears here, and nothing else does.
var Catalogs = map[string][]ai.Model{
	"amazon-bedrock":         AmazonBedrockModels,
	"ant-ling":               AntLingModels,
	"anthropic":              AnthropicModels,
	"azure-openai-responses": AzureOpenaiResponsesModels,
	"cerebras":               CerebrasModels,
	"cloudflare-ai-gateway":  CloudflareAIGatewayModels,
	"cloudflare-workers-ai":  CloudflareWorkersAIModels,
	"deepseek":               DeepseekModels,
	"fireworks":              FireworksModels,
	"github-copilot":         GithubCopilotModels,
	"google":                 GoogleModels,
	"google-vertex":          GoogleVertexModels,
	"groq":                   GroqModels,
	"huggingface":            HuggingfaceModels,
	"kimi-coding":            KimiCodingModels,
	"minimax":                MinimaxModels,
	"minimax-cn":             MinimaxCNModels,
	"mistral":                MistralModels,
	"moonshotai":             MoonshotaiModels,
	"moonshotai-cn":          MoonshotaiCNModels,
	"nvidia":                 NvidiaModels,
	"openai":                 OpenaiModels,
	"openai-codex":           OpenaiCodexModels,
	"opencode":               OpencodeModels,
	"opencode-go":            OpencodeGOModels,
	"openrouter":             OpenrouterModels,
	"qwen-token-plan":        QwenTokenPlanModels,
	"qwen-token-plan-cn":     QwenTokenPlanCNModels,
	"together":               TogetherModels,
	"vercel-ai-gateway":      VercelAIGatewayModels,
	"xai":                    XaiModels,
	"xiaomi":                 XiaomiModels,
	"xiaomi-token-plan-ams":  XiaomiTokenPlanAmsModels,
	"xiaomi-token-plan-cn":   XiaomiTokenPlanCNModels,
	"xiaomi-token-plan-sgp":  XiaomiTokenPlanSgpModels,
	"zai":                    ZaiModels,
	"zai-coding-cn":          ZaiCodingCNModels,
}
