// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// MoonshotaiCNModels is the compiled model catalog for "moonshotai-cn".
var MoonshotaiCNModels = []ai.Model{
	{
		ID: "kimi-k2-0711-preview", Name: "Kimi K2 0711",
		Api: ai.ApiOpenAICompletions, Provider: "moonshotai-cn", BaseURL: "https://api.moonshot.cn/v1",
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.6, Output: 2.5, CacheRead: 0.15}},
		ContextWindow: 131072, MaxTokens: 16384,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("deepseek"), SupportsStrictMode: boolptr(false)},
	},
	{
		ID: "kimi-k2-0905-preview", Name: "Kimi K2 0905",
		Api: ai.ApiOpenAICompletions, Provider: "moonshotai-cn", BaseURL: "https://api.moonshot.cn/v1",
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.6, Output: 2.5, CacheRead: 0.15}},
		ContextWindow: 262144, MaxTokens: 262144,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("deepseek"), SupportsStrictMode: boolptr(false)},
	},
	{
		ID: "kimi-k2-thinking", Name: "Kimi K2 Thinking",
		Api: ai.ApiOpenAICompletions, Provider: "moonshotai-cn", BaseURL: "https://api.moonshot.cn/v1",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.6, Output: 2.5, CacheRead: 0.15}},
		ContextWindow: 262144, MaxTokens: 262144,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("deepseek"), SupportsStrictMode: boolptr(false)},
	},
	{
		ID: "kimi-k2-thinking-turbo", Name: "Kimi K2 Thinking Turbo",
		Api: ai.ApiOpenAICompletions, Provider: "moonshotai-cn", BaseURL: "https://api.moonshot.cn/v1",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 1.15, Output: 8, CacheRead: 0.15}},
		ContextWindow: 262144, MaxTokens: 262144,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("deepseek"), SupportsStrictMode: boolptr(false)},
	},
	{
		ID: "kimi-k2-turbo-preview", Name: "Kimi K2 Turbo",
		Api: ai.ApiOpenAICompletions, Provider: "moonshotai-cn", BaseURL: "https://api.moonshot.cn/v1",
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 2.4, Output: 10, CacheRead: 0.6}},
		ContextWindow: 262144, MaxTokens: 262144,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("deepseek"), SupportsStrictMode: boolptr(false)},
	},
	{
		ID: "kimi-k2.5", Name: "Kimi K2.5",
		Api: ai.ApiOpenAICompletions, Provider: "moonshotai-cn", BaseURL: "https://api.moonshot.cn/v1",
		Reasoning:     true,
		Input:         []string{"text", "image"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.6, Output: 3, CacheRead: 0.1}},
		ContextWindow: 262144, MaxTokens: 262144,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("deepseek"), SupportsStrictMode: boolptr(false)},
	},
	{
		ID: "kimi-k2.6", Name: "Kimi K2.6",
		Api: ai.ApiOpenAICompletions, Provider: "moonshotai-cn", BaseURL: "https://api.moonshot.cn/v1",
		Reasoning:     true,
		Input:         []string{"text", "image"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.95, Output: 4, CacheRead: 0.16}},
		ContextWindow: 262144, MaxTokens: 262144,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("deepseek"), SupportsStrictMode: boolptr(false)},
	},
	{
		ID: "kimi-k2.7-code", Name: "Kimi K2.7 Code",
		Api: ai.ApiOpenAICompletions, Provider: "moonshotai-cn", BaseURL: "https://api.moonshot.cn/v1",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"off": nil},
		Input:            []string{"text", "image"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.95, Output: 4, CacheRead: 0.19}},
		ContextWindow:    262144, MaxTokens: 262144,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("deepseek"), SupportsStrictMode: boolptr(false)},
	},
	{
		ID: "kimi-k2.7-code-highspeed", Name: "Kimi K2.7 Code HighSpeed",
		Api: ai.ApiOpenAICompletions, Provider: "moonshotai-cn", BaseURL: "https://api.moonshot.cn/v1",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"off": nil},
		Input:            []string{"text", "image"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 1.9, Output: 8, CacheRead: 0.38}},
		ContextWindow:    262144, MaxTokens: 262144,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("deepseek"), SupportsStrictMode: boolptr(false)},
	},
	{
		ID: "kimi-k3", Name: "Kimi K3",
		Api: ai.ApiOpenAICompletions, Provider: "moonshotai-cn", BaseURL: "https://api.moonshot.cn/v1",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("high"), "low": strptr("low"), "max": strptr("max"), "medium": nil, "minimal": nil, "off": nil, "xhigh": nil},
		Input:            []string{"text", "image"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 3, Output: 15, CacheRead: 0.3}},
		ContextWindow:    1048576, MaxTokens: 131072,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(true), MaxTokensField: strptr("max_tokens"), RequiresReasoningContentOnAssistantMessages: boolptr(true), ThinkingFormat: strptr("openai"), SupportsStrictMode: boolptr(false), DeferredToolsMode: strptr("kimi")},
	},
}
