// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// OpenaiCodexModels is the compiled model catalog for "openai-codex".
var OpenaiCodexModels = []ai.Model{
	{
		ID: "gpt-5.3-codex-spark", Name: "GPT-5.3 Codex Spark",
		Api: ai.ApiOpenAICodexResponses, Provider: "openai-codex", BaseURL: "https://chatgpt.com/backend-api",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"minimal": strptr("low"), "xhigh": strptr("xhigh")},
		Input:            []string{"text"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 1.75, Output: 14, CacheRead: 0.175}},
		ContextWindow:    128000, MaxTokens: 128000,
		Compat: &ai.CompatFlags{SupportsOpenAIGrammarTools: boolptr(true)},
	},
	{
		ID: "gpt-5.4", Name: "GPT-5.4",
		Api: ai.ApiOpenAICodexResponses, Provider: "openai-codex", BaseURL: "https://chatgpt.com/backend-api",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"minimal": strptr("low"), "xhigh": strptr("xhigh")},
		Input:            []string{"text", "image"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 2.5, Output: 15, CacheRead: 0.25}, Tiers: []ai.ModelCostTier{{InputTokensAbove: 272000, ModelCostRates: ai.ModelCostRates{Input: 5, Output: 22.5, CacheRead: 0.5}}}},
		ContextWindow:    272000, MaxTokens: 128000,
		Compat: &ai.CompatFlags{SupportsOpenAIGrammarTools: boolptr(true), SupportsToolSearch: boolptr(true)},
	},
	{
		ID: "gpt-5.4-mini", Name: "GPT-5.4 mini",
		Api: ai.ApiOpenAICodexResponses, Provider: "openai-codex", BaseURL: "https://chatgpt.com/backend-api",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"minimal": strptr("low"), "xhigh": strptr("xhigh")},
		Input:            []string{"text", "image"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.75, Output: 4.5, CacheRead: 0.075}},
		ContextWindow:    272000, MaxTokens: 128000,
		Compat: &ai.CompatFlags{SupportsOpenAIGrammarTools: boolptr(true), SupportsToolSearch: boolptr(true)},
	},
	{
		ID: "gpt-5.5", Name: "GPT-5.5",
		Api: ai.ApiOpenAICodexResponses, Provider: "openai-codex", BaseURL: "https://chatgpt.com/backend-api",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"minimal": strptr("low"), "xhigh": strptr("xhigh")},
		Input:            []string{"text", "image"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 5, Output: 30, CacheRead: 0.5}, Tiers: []ai.ModelCostTier{{InputTokensAbove: 272000, ModelCostRates: ai.ModelCostRates{Input: 10, Output: 45, CacheRead: 1}}}},
		ContextWindow:    272000, MaxTokens: 128000,
		Compat: &ai.CompatFlags{SupportsOpenAIGrammarTools: boolptr(true), SupportsToolSearch: boolptr(true)},
	},
	{
		ID: "gpt-5.6-luna", Name: "GPT-5.6 Luna",
		Api: ai.ApiOpenAICodexResponses, Provider: "openai-codex", BaseURL: "https://chatgpt.com/backend-api",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"max": strptr("max"), "minimal": strptr("low"), "xhigh": strptr("xhigh")},
		Input:            []string{"text", "image"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 1, Output: 6, CacheRead: 0.1, CacheWrite: 1.25}, Tiers: []ai.ModelCostTier{{InputTokensAbove: 272000, ModelCostRates: ai.ModelCostRates{Input: 2, Output: 9, CacheRead: 0.2, CacheWrite: 2.5}}}},
		ContextWindow:    272000, MaxTokens: 128000,
		Compat: &ai.CompatFlags{SupportsOpenAIGrammarTools: boolptr(true), SupportsToolSearch: boolptr(true)},
	},
	{
		ID: "gpt-5.6-sol", Name: "GPT-5.6 Sol",
		Api: ai.ApiOpenAICodexResponses, Provider: "openai-codex", BaseURL: "https://chatgpt.com/backend-api",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"max": strptr("max"), "minimal": strptr("low"), "xhigh": strptr("xhigh")},
		Input:            []string{"text", "image"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 5, Output: 30, CacheRead: 0.5, CacheWrite: 6.25}, Tiers: []ai.ModelCostTier{{InputTokensAbove: 272000, ModelCostRates: ai.ModelCostRates{Input: 10, Output: 45, CacheRead: 1, CacheWrite: 12.5}}}},
		ContextWindow:    272000, MaxTokens: 128000,
		Compat: &ai.CompatFlags{SupportsOpenAIGrammarTools: boolptr(true), SupportsToolSearch: boolptr(true)},
	},
	{
		ID: "gpt-5.6-terra", Name: "GPT-5.6 Terra",
		Api: ai.ApiOpenAICodexResponses, Provider: "openai-codex", BaseURL: "https://chatgpt.com/backend-api",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"max": strptr("max"), "minimal": strptr("low"), "xhigh": strptr("xhigh")},
		Input:            []string{"text", "image"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 2.5, Output: 15, CacheRead: 0.25, CacheWrite: 3.125}, Tiers: []ai.ModelCostTier{{InputTokensAbove: 272000, ModelCostRates: ai.ModelCostRates{Input: 5, Output: 22.5, CacheRead: 0.5, CacheWrite: 6.25}}}},
		ContextWindow:    272000, MaxTokens: 128000,
		Compat: &ai.CompatFlags{SupportsOpenAIGrammarTools: boolptr(true), SupportsToolSearch: boolptr(true)},
	},
}
