// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// CerebrasModels is the compiled model catalog for "cerebras".
var CerebrasModels = []ai.Model{
	{
		ID: "gemma-4-31b", Name: "Gemma 4 31B IT",
		Api: ai.ApiOpenAICompletions, Provider: "cerebras", BaseURL: "https://api.cerebras.ai/v1",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("high"), "low": strptr("low"), "max": nil, "medium": strptr("medium"), "minimal": nil, "off": strptr("none"), "xhigh": nil},
		Input:            []string{"text", "image"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.99, Output: 1.49}},
		ContextWindow:    131072, MaxTokens: 40960,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false)},
	},
	{
		ID: "gpt-oss-120b", Name: "GPT OSS 120B",
		Api: ai.ApiOpenAICompletions, Provider: "cerebras", BaseURL: "https://api.cerebras.ai/v1",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("high"), "low": strptr("low"), "max": nil, "medium": strptr("medium"), "minimal": nil, "off": nil, "xhigh": nil},
		Input:            []string{"text"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.35, Output: 0.75}},
		ContextWindow:    131072, MaxTokens: 40960,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false)},
	},
	{
		ID: "zai-glm-4.7", Name: "Z.AI GLM-4.7",
		Api: ai.ApiOpenAICompletions, Provider: "cerebras", BaseURL: "https://api.cerebras.ai/v1",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": nil, "low": nil, "max": nil, "medium": nil, "minimal": nil, "off": strptr("none"), "xhigh": nil},
		Input:            []string{"text"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 2.25, Output: 2.75, CacheRead: 2.25}},
		ContextWindow:    131072, MaxTokens: 40960,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false)},
	},
}
