// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// AntLingModels is the compiled model catalog for "ant-ling".
var AntLingModels = []ai.Model{
	{
		ID: "Ling-2.6-flash", Name: "Ling 2.6 Flash",
		Api: ai.ApiOpenAICompletions, Provider: "ant-ling", BaseURL: "https://api.ant-ling.com/v1",
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.01, Output: 0.02}},
		ContextWindow: 262144, MaxTokens: 65536,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("ant-ling"), SupportsLongCacheRetention: boolptr(false)},
	},
	{
		ID: "Ling-2.6-1T", Name: "Ling 2.6 1T",
		Api: ai.ApiOpenAICompletions, Provider: "ant-ling", BaseURL: "https://api.ant-ling.com/v1",
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.06, Output: 0.25}},
		ContextWindow: 262144, MaxTokens: 65536,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("ant-ling"), SupportsLongCacheRetention: boolptr(false)},
	},
	{
		ID: "Ring-2.6-1T", Name: "Ring 2.6 1T",
		Api: ai.ApiOpenAICompletions, Provider: "ant-ling", BaseURL: "https://api.ant-ling.com/v1",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("high"), "low": nil, "medium": nil, "minimal": nil, "off": nil, "xhigh": strptr("xhigh")},
		Input:            []string{"text"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.06, Output: 0.25}},
		ContextWindow:    262144, MaxTokens: 65536,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("ant-ling"), SupportsLongCacheRetention: boolptr(false)},
	},
}
