// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// KimiCodingModels is the compiled model catalog for "kimi-coding".
var KimiCodingModels = []ai.Model{
	{
		ID: "k3", Name: "Kimi K3",
		Api: ai.ApiAnthropicMessages, Provider: "kimi-coding", BaseURL: "https://api.kimi.com/coding",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("high"), "low": strptr("low"), "max": strptr("max"), "medium": nil, "minimal": nil, "off": nil, "xhigh": nil},
		Input:            []string{"text", "image"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 3, Output: 15, CacheRead: 0.3}},
		ContextWindow:    1048576, MaxTokens: 131072,
		Headers: map[string]string{"User-Agent": "KimiCLI/1.5"},
		Compat:  &ai.CompatFlags{ForceAdaptiveThinking: boolptr(true), AllowEmptySignature: boolptr(true)},
	},
	{
		ID: "k3-256k", Name: "Kimi K3-256K",
		Api: ai.ApiAnthropicMessages, Provider: "kimi-coding", BaseURL: "https://api.kimi.com/coding",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("high"), "low": strptr("low"), "max": strptr("max"), "medium": nil, "minimal": nil, "off": nil, "xhigh": nil},
		Input:            []string{"text", "image"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{}},
		ContextWindow:    262144, MaxTokens: 131072,
		Headers: map[string]string{"User-Agent": "KimiCLI/1.5"},
		Compat:  &ai.CompatFlags{ForceAdaptiveThinking: boolptr(true)},
	},
	{
		ID: "kimi-for-coding", Name: "Kimi K2.7 Code",
		Api: ai.ApiAnthropicMessages, Provider: "kimi-coding", BaseURL: "https://api.kimi.com/coding",
		Reasoning:     true,
		Input:         []string{"text", "image"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.95, Output: 4, CacheRead: 0.19}},
		ContextWindow: 262144, MaxTokens: 32768,
		Headers: map[string]string{"User-Agent": "KimiCLI/1.5"},
		Compat:  &ai.CompatFlags{ForceAdaptiveThinking: boolptr(true), AllowEmptySignature: boolptr(true)},
	},
	{
		ID: "kimi-for-coding-highspeed", Name: "Kimi For Coding HighSpeed",
		Api: ai.ApiAnthropicMessages, Provider: "kimi-coding", BaseURL: "https://api.kimi.com/coding",
		Reasoning:     true,
		Input:         []string{"text", "image"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 1.9, Output: 8, CacheRead: 0.38}},
		ContextWindow: 262144, MaxTokens: 32768,
		Headers: map[string]string{"User-Agent": "KimiCLI/1.5"},
		Compat:  &ai.CompatFlags{ForceAdaptiveThinking: boolptr(true)},
	},
}
