// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// ZaiCodingCNModels is the compiled model catalog for "zai-coding-cn".
var ZaiCodingCNModels = []ai.Model{
	{
		ID: "glm-4.5-air", Name: "GLM-4.5-Air",
		Api: ai.ApiOpenAICompletions, Provider: "zai-coding-cn", BaseURL: "https://open.bigmodel.cn/api/coding/paas/v4",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{}},
		ContextWindow: 131072, MaxTokens: 98304,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("zai")},
	},
	{
		ID: "glm-4.7", Name: "GLM-4.7",
		Api: ai.ApiOpenAICompletions, Provider: "zai-coding-cn", BaseURL: "https://open.bigmodel.cn/api/coding/paas/v4",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{}},
		ContextWindow: 204800, MaxTokens: 131072,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("zai"), ZaiToolStream: boolptr(true)},
	},
	{
		ID: "glm-5-turbo", Name: "GLM-5-Turbo",
		Api: ai.ApiOpenAICompletions, Provider: "zai-coding-cn", BaseURL: "https://open.bigmodel.cn/api/coding/paas/v4",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{}},
		ContextWindow: 200000, MaxTokens: 131072,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("zai"), ZaiToolStream: boolptr(true)},
	},
	{
		ID: "glm-5.1", Name: "GLM-5.1",
		Api: ai.ApiOpenAICompletions, Provider: "zai-coding-cn", BaseURL: "https://open.bigmodel.cn/api/coding/paas/v4",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{}},
		ContextWindow: 200000, MaxTokens: 131072,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("zai"), ZaiToolStream: boolptr(true)},
	},
	{
		ID: "glm-5.2", Name: "GLM-5.2",
		Api: ai.ApiOpenAICompletions, Provider: "zai-coding-cn", BaseURL: "https://open.bigmodel.cn/api/coding/paas/v4",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("high"), "low": strptr("high"), "max": strptr("max"), "medium": strptr("high"), "minimal": nil},
		Input:            []string{"text"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{}},
		ContextWindow:    1000000, MaxTokens: 131072,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(true), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("zai"), ZaiToolStream: boolptr(true)},
	},
	{
		ID: "glm-5v-turbo", Name: "GLM-5V-Turbo",
		Api: ai.ApiOpenAICompletions, Provider: "zai-coding-cn", BaseURL: "https://open.bigmodel.cn/api/coding/paas/v4",
		Reasoning:     true,
		Input:         []string{"text", "image"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{}},
		ContextWindow: 200000, MaxTokens: 131072,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false), MaxTokensField: strptr("max_tokens"), ThinkingFormat: strptr("zai"), ZaiToolStream: boolptr(true)},
	},
}
