// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// XiaomiTokenPlanCNModels is the compiled model catalog for "xiaomi-token-plan-cn".
var XiaomiTokenPlanCNModels = []ai.Model{
	{
		ID: "mimo-v2-pro", Name: "MiMo-V2-Pro",
		Api: ai.ApiOpenAICompletions, Provider: "xiaomi-token-plan-cn", BaseURL: "https://token-plan-cn.xiaomimimo.com/v1",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{}},
		ContextWindow: 1048576, MaxTokens: 131072,
		Compat: &ai.CompatFlags{RequiresReasoningContentOnAssistantMessages: boolptr(true), ThinkingFormat: strptr("deepseek")},
	},
	{
		ID: "mimo-v2.5", Name: "MiMo-V2.5",
		Api: ai.ApiOpenAICompletions, Provider: "xiaomi-token-plan-cn", BaseURL: "https://token-plan-cn.xiaomimimo.com/v1",
		Reasoning:     true,
		Input:         []string{"text", "image"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{}},
		ContextWindow: 1048576, MaxTokens: 131072,
		Compat: &ai.CompatFlags{RequiresReasoningContentOnAssistantMessages: boolptr(true), ThinkingFormat: strptr("deepseek")},
	},
	{
		ID: "mimo-v2.5-pro", Name: "MiMo-V2.5-Pro",
		Api: ai.ApiOpenAICompletions, Provider: "xiaomi-token-plan-cn", BaseURL: "https://token-plan-cn.xiaomimimo.com/v1",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{}},
		ContextWindow: 1048576, MaxTokens: 131072,
		Compat: &ai.CompatFlags{RequiresReasoningContentOnAssistantMessages: boolptr(true), ThinkingFormat: strptr("deepseek")},
	},
}
