// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// XiaomiModels is the compiled model catalog for "xiaomi".
var XiaomiModels = []ai.Model{
	{
		ID: "mimo-v2-flash", Name: "MiMo-V2-Flash",
		Api: ai.ApiOpenAICompletions, Provider: "xiaomi", BaseURL: "https://api.xiaomimimo.com/v1",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.14, Output: 0.28, CacheRead: 0.0028}},
		ContextWindow: 262144, MaxTokens: 65536,
		Compat: &ai.CompatFlags{RequiresReasoningContentOnAssistantMessages: boolptr(true), ThinkingFormat: strptr("deepseek")},
	},
	{
		ID: "mimo-v2-omni", Name: "MiMo-V2-Omni",
		Api: ai.ApiOpenAICompletions, Provider: "xiaomi", BaseURL: "https://api.xiaomimimo.com/v1",
		Reasoning:     true,
		Input:         []string{"text", "image"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.14, Output: 0.28, CacheRead: 0.0028}},
		ContextWindow: 262144, MaxTokens: 131072,
		Compat: &ai.CompatFlags{RequiresReasoningContentOnAssistantMessages: boolptr(true), ThinkingFormat: strptr("deepseek")},
	},
	{
		ID: "mimo-v2-pro", Name: "MiMo-V2-Pro",
		Api: ai.ApiOpenAICompletions, Provider: "xiaomi", BaseURL: "https://api.xiaomimimo.com/v1",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.435, Output: 0.87, CacheRead: 0.0036}},
		ContextWindow: 1048576, MaxTokens: 131072,
		Compat: &ai.CompatFlags{RequiresReasoningContentOnAssistantMessages: boolptr(true), ThinkingFormat: strptr("deepseek")},
	},
	{
		ID: "mimo-v2.5", Name: "MiMo-V2.5",
		Api: ai.ApiOpenAICompletions, Provider: "xiaomi", BaseURL: "https://api.xiaomimimo.com/v1",
		Reasoning:     true,
		Input:         []string{"text", "image"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.14, Output: 0.28, CacheRead: 0.0028}},
		ContextWindow: 1048576, MaxTokens: 131072,
		Compat: &ai.CompatFlags{RequiresReasoningContentOnAssistantMessages: boolptr(true), ThinkingFormat: strptr("deepseek")},
	},
	{
		ID: "mimo-v2.5-pro", Name: "MiMo-V2.5-Pro",
		Api: ai.ApiOpenAICompletions, Provider: "xiaomi", BaseURL: "https://api.xiaomimimo.com/v1",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.435, Output: 0.87, CacheRead: 0.0036}},
		ContextWindow: 1048576, MaxTokens: 131072,
		Compat: &ai.CompatFlags{RequiresReasoningContentOnAssistantMessages: boolptr(true), ThinkingFormat: strptr("deepseek")},
	},
	{
		ID: "mimo-v2.5-pro-ultraspeed", Name: "MiMo-V2.5-Pro-UltraSpeed",
		Api: ai.ApiOpenAICompletions, Provider: "xiaomi", BaseURL: "https://api.xiaomimimo.com/v1",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 1.305, Output: 2.61, CacheRead: 0.0108}},
		ContextWindow: 1048576, MaxTokens: 131072,
		Compat: &ai.CompatFlags{RequiresReasoningContentOnAssistantMessages: boolptr(true), ThinkingFormat: strptr("deepseek")},
	},
}
