// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// GroqModels is the compiled model catalog for "groq".
var GroqModels = []ai.Model{
	{
		ID: "llama-3.1-8b-instant", Name: "Llama 3.1 8B",
		Api: ai.ApiOpenAICompletions, Provider: "groq", BaseURL: "https://api.groq.com/openai/v1",
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.05, Output: 0.08}},
		ContextWindow: 131072, MaxTokens: 131072,
	},
	{
		ID: "llama-3.3-70b-versatile", Name: "Llama 3.3 70B",
		Api: ai.ApiOpenAICompletions, Provider: "groq", BaseURL: "https://api.groq.com/openai/v1",
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.59, Output: 0.79}},
		ContextWindow: 131072, MaxTokens: 32768,
	},
	{
		ID: "meta-llama/llama-4-scout-17b-16e-instruct", Name: "Llama 4 Scout 17B 16E",
		Api: ai.ApiOpenAICompletions, Provider: "groq", BaseURL: "https://api.groq.com/openai/v1",
		Input:         []string{"text", "image"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.11, Output: 0.34}},
		ContextWindow: 131072, MaxTokens: 8192,
	},
	{
		ID: "openai/gpt-oss-120b", Name: "GPT OSS 120B",
		Api: ai.ApiOpenAICompletions, Provider: "groq", BaseURL: "https://api.groq.com/openai/v1",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("high"), "low": strptr("low"), "max": nil, "medium": strptr("medium"), "minimal": nil, "off": nil, "xhigh": nil},
		Input:            []string{"text"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.15, Output: 0.6, CacheRead: 0.075}},
		ContextWindow:    131072, MaxTokens: 65536,
	},
	{
		ID: "openai/gpt-oss-20b", Name: "GPT OSS 20B",
		Api: ai.ApiOpenAICompletions, Provider: "groq", BaseURL: "https://api.groq.com/openai/v1",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("high"), "low": strptr("low"), "max": nil, "medium": strptr("medium"), "minimal": nil, "off": nil, "xhigh": nil},
		Input:            []string{"text"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.075, Output: 0.3, CacheRead: 0.0375}},
		ContextWindow:    131072, MaxTokens: 65536,
	},
	{
		ID: "openai/gpt-oss-safeguard-20b", Name: "Safety GPT OSS 20B",
		Api: ai.ApiOpenAICompletions, Provider: "groq", BaseURL: "https://api.groq.com/openai/v1",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("high"), "low": strptr("low"), "max": nil, "medium": strptr("medium"), "minimal": nil, "off": nil, "xhigh": nil},
		Input:            []string{"text"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.075, Output: 0.3}},
		ContextWindow:    131072, MaxTokens: 65536,
	},
	{
		ID: "qwen/qwen3-32b", Name: "Qwen3-32B",
		Api: ai.ApiOpenAICompletions, Provider: "groq", BaseURL: "https://api.groq.com/openai/v1",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("default"), "low": nil, "max": nil, "medium": nil, "minimal": nil, "off": strptr("none"), "xhigh": nil},
		Input:            []string{"text"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.29, Output: 0.59}},
		ContextWindow:    131072, MaxTokens: 40960,
	},
}
