// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// XaiModels is the compiled model catalog for "xai".
var XaiModels = []ai.Model{
	{
		ID: "grok-4.3", Name: "Grok 4.3",
		Api: ai.ApiOpenAICompletions, Provider: "xai", BaseURL: "https://api.x.ai/v1",
		Reasoning:     true,
		Input:         []string{"text", "image"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 1.25, Output: 2.5, CacheRead: 0.2}},
		ContextWindow: 1000000, MaxTokens: 30000,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false)},
	},
	{
		ID: "grok-4.5", Name: "Grok 4.5",
		Api: ai.ApiOpenAIResponses, Provider: "xai", BaseURL: "https://api.x.ai/v1",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("high"), "low": strptr("low"), "max": nil, "medium": strptr("medium"), "minimal": nil, "off": nil, "xhigh": nil},
		Input:            []string{"text", "image"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 2, Output: 6, CacheRead: 0.3}},
		ContextWindow:    500000, MaxTokens: 500000,
		Compat: &ai.CompatFlags{SupportsLongCacheRetention: boolptr(false)},
	},
	{
		ID: "grok-build-0.1", Name: "Grok Build 0.1",
		Api: ai.ApiOpenAICompletions, Provider: "xai", BaseURL: "https://api.x.ai/v1",
		Reasoning:     true,
		Input:         []string{"text", "image"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 1, Output: 2, CacheRead: 0.2}},
		ContextWindow: 256000, MaxTokens: 256000,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), SupportsReasoningEffort: boolptr(false)},
	},
}
