// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// DeepseekModels is the compiled model catalog for "deepseek".
var DeepseekModels = []ai.Model{
	{
		ID: "deepseek-v4-flash", Name: "DeepSeek V4 Flash",
		Api: ai.ApiOpenAICompletions, Provider: "deepseek", BaseURL: "https://api.deepseek.com",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("high"), "low": nil, "max": strptr("max"), "medium": nil, "minimal": nil},
		Input:            []string{"text"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.14, Output: 0.28, CacheRead: 0.0028}},
		ContextWindow:    1000000, MaxTokens: 384000,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), RequiresReasoningContentOnAssistantMessages: boolptr(true), ThinkingFormat: strptr("deepseek")},
	},
	{
		ID: "deepseek-v4-pro", Name: "DeepSeek V4 Pro",
		Api: ai.ApiOpenAICompletions, Provider: "deepseek", BaseURL: "https://api.deepseek.com",
		Reasoning:        true,
		ThinkingLevelMap: ai.ThinkingLevelMap{"high": strptr("high"), "low": nil, "max": strptr("max"), "medium": nil, "minimal": nil},
		Input:            []string{"text"},
		Cost:             ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.435, Output: 0.87, CacheRead: 0.003625}},
		ContextWindow:    1000000, MaxTokens: 384000,
		Compat: &ai.CompatFlags{SupportsStore: boolptr(false), SupportsDeveloperRole: boolptr(false), RequiresReasoningContentOnAssistantMessages: boolptr(true), ThinkingFormat: strptr("deepseek")},
	},
}
