// Code generated by cmd/tau-genmodels. DO NOT EDIT.

package catalog

import "github.com/ihavespoons/tau/ai"

// MinimaxModels is the compiled model catalog for "minimax".
var MinimaxModels = []ai.Model{
	{
		ID: "MiniMax-M2.7", Name: "MiniMax-M2.7",
		Api: ai.ApiAnthropicMessages, Provider: "minimax", BaseURL: "https://api.minimax.io/anthropic",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.3, Output: 1.2, CacheRead: 0.06, CacheWrite: 0.375}},
		ContextWindow: 204800, MaxTokens: 131072,
	},
	{
		ID: "MiniMax-M2.7-highspeed", Name: "MiniMax-M2.7-highspeed",
		Api: ai.ApiAnthropicMessages, Provider: "minimax", BaseURL: "https://api.minimax.io/anthropic",
		Reasoning:     true,
		Input:         []string{"text"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.6, Output: 2.4, CacheRead: 0.06, CacheWrite: 0.375}},
		ContextWindow: 204800, MaxTokens: 131072,
	},
	{
		ID: "MiniMax-M3", Name: "MiniMax-M3",
		Api: ai.ApiAnthropicMessages, Provider: "minimax", BaseURL: "https://api.minimax.io/anthropic",
		Reasoning:     true,
		Input:         []string{"text", "image"},
		Cost:          ai.ModelCost{ModelCostRates: ai.ModelCostRates{Input: 0.3, Output: 1.2, CacheRead: 0.06}},
		ContextWindow: 1000000, MaxTokens: 128000,
	},
}
