// Code generated by cmd/gen-wire-ts. DO NOT EDIT.
//
// These declarations are generated from the Go types in extension/wire, which
// are the definition of the subprocess extension protocol. Editing this file
// makes the two sides disagree without anything failing to compile; change the
// Go types and regenerate instead.
//
//   go generate ./extension/wire/

/** Frame type names, as they appear on the wire. */
export const enum FrameName {
	Init = "init",
	Event = "event",
	ToolExecute = "tool_execute",
	Command = "command",
	Completions = "completions",
	Shortcut = "shortcut",
	Render = "render",
	Cancel = "cancel",
	Reply = "reply",
	Shutdown = "shutdown",
	InitResult = "init_result",
	Result = "result",
	ToolUpdate = "tool_update",
	UIRequest = "ui_request",
	Action = "action",
	Log = "log",
}

/**
 * Action asks the host to act on the session.
 */
export interface Action {
	type: string;
	id: string;
	/**
	 * Method is one of: sendMessage, setSessionName, getSessionName, exec,
	 * getActiveTools, setActiveTools, getModel, setModel, getThinkingLevel,
	 * setThinkingLevel, registerTool, unregisterTool, emit.
	 */
	method: string;
	params?: unknown;
}

/**
 * Cancel abandons an in-flight request.
 */
export interface Cancel {
	type: string;
	id: string;
}

/**
 * Command runs a registered slash command.
 */
export interface Command {
	type: string;
	id: string;
	generation: number;
	name: string;
	args?: string;
}

/**
 * CommandDecl is a slash command the extension registers.
 */
export interface CommandDecl {
	name: string;
	description?: string;
	/**
	 * Completions declares that the extension answers completions frames for
	 * this command. Without it the host never asks.
	 */
	completions?: boolean;
}

/**
 * CompletionItem is one autocomplete suggestion.
 */
export interface CompletionItem {
	value: string;
	label?: string;
	description?: string;
}

/**
 * Completions asks for argument completions.
 */
export interface Completions {
	type: string;
	id: string;
	name: string;
	prefix?: string;
}

/**
 * CompletionsResult answers a Completions request.
 */
export interface CompletionsResult {
	items?: CompletionItem[];
}

/**
 * Envelope is enough of a frame to route it. The full frame is decoded again
 * into its concrete type once the direction and kind are known.
 */
export interface Envelope {
	type: string;
	/**
	 * ID correlates a request with its result. Frames that are neither carry
	 * none.
	 */
	id?: string;
}

/**
 * Event dispatches one extension event.
 */
export interface Event {
	type: string;
	id: string;
	/**
	 * Event is the event type name, matching extension.EventType.
	 */
	event: string;
	/**
	 * Generation stamps the session this event belongs to. A result arriving
	 * with a stale generation is discarded: the session it referred to is
	 * gone, and applying its decision to the current one would be wrong.
	 */
	generation: number;
	/**
	 * Payload is the event struct, marshalled with its own JSON tags.
	 */
	payload?: unknown;
	/**
	 * NoReply marks an event whose result the host will not wait for. Used
	 * for the notification-only events, where the extension's answer cannot
	 * change anything and waiting would put a subprocess round trip in the
	 * middle of the agent loop.
	 */
	noReply?: boolean;
}

/**
 * ExecParams runs a shell command in the session's environment.
 */
export interface ExecParams {
	command: string;
}

/**
 * ExecResult is the outcome of an Exec action. A non-zero exit code is data,
 * not an error — the same contract the built-in bash tool has.
 */
export interface ExecResult {
	output: string;
	exitCode: number;
}

/**
 * FlagDecl is a CLI flag the extension registers.
 */
export interface FlagDecl {
	name: string;
	description?: string;
	/**
	 * Type is "bool" or "string".
	 */
	type: string;
	default?: unknown;
}

/**
 * Init opens the connection.
 */
export interface Init {
	type: string;
	/**
	 * Protocol is the host's wire version.
	 */
	protocol: number;
	/**
	 * Name is the extension's identity in diagnostics, derived from its path.
	 */
	name: string;
	/**
	 * Path is the file or directory the extension was loaded from.
	 */
	path: string;
	/**
	 * Cwd is the session's working directory.
	 */
	cwd: string;
	/**
	 * Mode is always "rpc" for a subprocess extension, whatever the host's
	 * own mode is. Pi extensions branch on ctx.mode !== "tui" to decide
	 * whether a UI exists, and over a wire it does not in the sense they
	 * mean: there is no component tree to mount into, only the request
	 * shapes in this protocol.
	 */
	mode: string;
	/**
	 * Trusted reports whether project-scoped resources were allowed to load.
	 * An extension reading files from the project must respect it.
	 */
	trusted: boolean;
	/**
	 * Generation is the session generation this connection starts at.
	 */
	generation: number;
	/**
	 * Flags carries values for flags the extension declared on a previous
	 * run. It is empty on a first connection, since flags are not known until
	 * the extension declares them.
	 */
	flags?: Record<string, unknown>;
	/**
	 * TauVersion lets an extension branch on host capabilities.
	 */
	tauVersion?: string;
}

/**
 * InitResult completes the handshake.
 *
 * It is declarative on purpose. The host learns everything it needs to route
 * work in one round trip, and an event nobody subscribed to is never
 * serialized, never written, and never woken up for.
 */
export interface InitResult {
	type: string;
	/**
	 * Protocol is the extension's wire version.
	 */
	protocol: number;
	/**
	 * Name overrides the host's guess at the extension's name.
	 */
	name?: string;
	/**
	 * Subscriptions lists the event types the extension handles. Anything not
	 * listed is never sent.
	 */
	subscriptions?: string[];
	tools?: ToolDecl[];
	commands?: CommandDecl[];
	shortcuts?: ShortcutDecl[];
	flags?: FlagDecl[];
	renderers?: RendererDecl[];
	/**
	 * Warnings are non-fatal load complaints — an unsupported API the shim
	 * stubbed out, a deprecated import. The host surfaces them once.
	 */
	warnings?: string[];
	/**
	 * Error fails the handshake. The extension is not loaded.
	 */
	error?: string;
}

/**
 * Log writes a diagnostic line. It expects no reply.
 */
export interface Log {
	type: string;
	/**
	 * Level is "debug", "info", "warn", or "error".
	 */
	level?: string;
	message: string;
}

/**
 * ModelInfo describes the active model in an action reply.
 */
export interface ModelInfo {
	provider: string;
	id: string;
	name?: string;
	/**
	 * ContextWindow and MaxTokens let an extension budget its own additions
	 * to the context without asking the host to do the arithmetic.
	 */
	contextWindow?: number;
	maxTokens?: number;
	reasoning?: boolean;
}

/**
 * ModelParams selects a model by provider and id.
 */
export interface ModelParams {
	provider: string;
	modelId: string;
}

/**
 * NameParams carries a single name, for setSessionName.
 */
export interface NameParams {
	name: string;
}

/**
 * RegisterToolParams adds a tool after the handshake. An MCP server that
 * announces tools/list_changed mid-session needs this; so does any extension
 * whose tool set depends on something it learns later.
 */
export interface RegisterToolParams {
	tool: ToolDecl;
}

/**
 * Render asks a renderer for its lines.
 */
export interface Render {
	type: string;
	id: string;
	/**
	 * Kind is "message" or "entry".
	 */
	kind: string;
	/**
	 * Width is the available column count.
	 */
	width: number;
	/**
	 * Payload is the message or entry to render.
	 */
	payload?: unknown;
}

/**
 * RenderResult answers a Render request. Lines may carry ANSI styling; the
 * host does not re-wrap them.
 */
export interface RenderResult {
	lines?: string[];
}

/**
 * RendererDecl is a renderer the extension registers.
 */
export interface RendererDecl {
	/**
	 * Kind is "message" or "entry".
	 */
	kind: string;
	/**
	 * Selector narrows what the renderer claims: a message role, or an entry
	 * type. Empty claims everything of that kind.
	 */
	selector?: string;
}

/**
 * Reply answers a UIRequest or an Action.
 */
export interface Reply {
	type: string;
	id: string;
	payload?: unknown;
	/**
	 * Cancelled reports that the user dismissed a dialog. It is distinct from
	 * an error: nothing went wrong, the answer is simply absent.
	 */
	cancelled?: boolean;
	error?: string;
}

/**
 * Result answers a host request.
 *
 * The payload shape follows from the request: an Event's result is the event's
 * own result struct, a ToolExecute's is a ToolResult, a Completions' is a
 * CompletionItem list, a Render's is a line list. A Command and a Shortcut
 * carry no payload.
 *
 * A nil Payload means "no opinion" and is not the same as an empty object: for
 * most events the composition policy distinguishes them, and collapsing the
 * two would silently turn "I did not decide" into "I decided the zero value".
 */
export interface Result {
	type: string;
	id: string;
	payload?: unknown;
	/**
	 * Error reports a handler failure, and what the host does with it depends
	 * on the event.
	 *
	 * tool_call fails CLOSED: an error, a timeout, a crash, or a suspended
	 * extension all block the call. A permission gate that stops answering
	 * must not be read as consent, so silence is a refusal.
	 *
	 * Every other event fails open: the failure is reported to the user and
	 * the agent carries on as though the extension had no opinion. A broken
	 * extension must not be able to stop the agent.
	 */
	error?: string;
}

/**
 * SendMessageParams delivers a message into the conversation.
 */
export interface SendMessageParams {
	message: unknown;
	/**
	 * DeliverAs is "steer", "followUp", or empty for the next turn.
	 */
	deliverAs?: string;
}

/**
 * Shortcut fires a registered key binding.
 */
export interface Shortcut {
	type: string;
	id: string;
	generation: number;
	key: string;
}

/**
 * ShortcutDecl is a key binding the extension registers.
 */
export interface ShortcutDecl {
	key: string;
	description?: string;
}

/**
 * Shutdown asks the extension to exit.
 */
export interface Shutdown {
	type: string;
	/**
	 * Reason is "exit", "reload", or "suspended".
	 */
	reason?: string;
}

/**
 * StringResult answers the actions that return one string.
 */
export interface StringResult {
	value?: string;
}

/**
 * StringsResult answers the actions that return a list of names.
 */
export interface StringsResult {
	values?: string[];
}

/**
 * ThinkingParams sets the thinking level.
 */
export interface ThinkingParams {
	level: string;
}

/**
 * ToolDecl is a tool the extension registers.
 */
export interface ToolDecl {
	name: string;
	description?: string;
	/**
	 * Parameters is a JSON Schema object. It is passed through to the
	 * provider unchanged, exactly as an in-process tool's schema is.
	 */
	parameters?: unknown;
	/**
	 * Streaming declares that the extension emits tool_update frames while
	 * the tool runs. Hosts that cannot show partial results ignore it.
	 */
	streaming?: boolean;
}

/**
 * ToolExecute runs a registered tool.
 */
export interface ToolExecute {
	type: string;
	id: string;
	generation: number;
	tool: string;
	callId: string;
	args?: unknown;
}

/**
 * ToolNamesParams carries a tool-name list, for setActiveTools.
 */
export interface ToolNamesParams {
	names: string[];
}

/**
 * ToolResultPayload answers a ToolExecute request.
 */
export interface ToolResultPayload {
	/**
	 * Output is the text handed back to the model.
	 */
	output: string;
	/**
	 * Details is arbitrary structured data kept in the session entry and
	 * offered to renderers. It never reaches the model.
	 */
	details?: unknown;
	/**
	 * IsError marks a failed execution. Following the same contract as an
	 * in-process tool, it is a result rather than a transport failure: the
	 * model sees the message and can react.
	 */
	isError?: boolean;
}

/**
 * ToolUpdate streams a partial tool result. It expects no reply.
 */
export interface ToolUpdate {
	type: string;
	/**
	 * ID is the ToolExecute request being updated.
	 */
	id: string;
	partial?: unknown;
}

/**
 * UIConfirmed answers confirm.
 */
export interface UIConfirmed {
	confirmed: boolean;
}

/**
 * UIRequest asks the host to interact with the user.
 *
 * The field names are Pi's, verbatim from its RpcExtensionUIRequest. A Pi
 * extension running under the shim produces exactly these shapes already, and
 * an rpc client written against Pi understands them without a translation
 * layer on either side.
 */
export interface UIRequest {
	type: string;
	id: string;
	/**
	 * Method is one of: select, confirm, input, editor, notify, setStatus,
	 * setWidget, setTitle, set_editor_text.
	 */
	method: string;
	title?: string;
	message?: string;
	options?: string[];
	/**
	 * Timeout is in milliseconds. Zero waits indefinitely.
	 */
	timeout?: number;
	placeholder?: string;
	prefill?: string;
	/**
	 * NotifyType is "info", "warning", or "error".
	 */
	notifyType?: string;
	statusKey?: string;
	/**
	 * StatusText is a pointer so that clearing a status (null) is
	 * distinguishable from setting it to the empty string.
	 */
	statusText?: string | null;
	widgetKey?: string;
	/**
	 * WidgetLines nil removes the widget.
	 */
	widgetLines?: string[];
	/**
	 * WidgetPlacement is "aboveEditor" or "belowEditor".
	 */
	widgetPlacement?: string;
	text?: string;
}

/**
 * UIValue answers select, input, and editor. Pi's client sends exactly this
 * shape back, so a client written against Pi needs no translation.
 */
export interface UIValue {
	value: string;
}

