package session

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ihavespoons/tau/ai"
)

// The directory name must match Pi byte-for-byte, or the interop importer
// cannot find a Pi user's sessions. Expectations below were generated by
// running Pi's own expression in node:
//
//	`--${cwd.replace(/^[/\\]/, "").replace(/[/\\:]/g, "-")}--`
//
// Note the Windows case yields a double dash: the drive colon and the
// following backslash each become one.
func TestEncodeCwdMatchesPi(t *testing.T) {
	tests := []struct{ cwd, want string }{
		{"/Users/ben/Code/tau", "--Users-ben-Code-tau--"},
		{"/tmp/x", "--tmp-x--"},
		{"relative/path", "--relative-path--"},
		{`C:\Users\ben\code`, "--C--Users-ben-code--"},
		{"/", "----"},
		{"", "----"},
		{"//double/slash", "---double-slash--"},
		{"/a:b/c", "--a-b-c--"},
	}
	for _, tc := range tests {
		if got := EncodeCwd(tc.cwd); got != tc.want {
			t.Errorf("EncodeCwd(%q) = %q, want %q", tc.cwd, got, tc.want)
		}
	}
}

func TestSessionFileName(t *testing.T) {
	got := sessionFileName("2026-07-28T14:00:00.000Z", "01937b2e-4a1c-7c3f")
	want := "2026-07-28T14-00-00-000Z_01937b2e-4a1c-7c3f.jsonl"
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRepoCreateAndOpen(t *testing.T) {
	ctx := context.Background()
	root := t.TempDir()
	repo := NewJSONLRepo(root)

	s, err := repo.Create(ctx, CreateSessionOptions{Cwd: "/Users/ben/proj"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := s.AppendMessage(ctx, userMsg("hello")); err != nil {
		t.Fatal(err)
	}

	meta, err := s.Metadata(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(meta.Path, "--Users-ben-proj--") {
		t.Errorf("path %q should sit under the encoded cwd directory", meta.Path)
	}
	if !strings.HasSuffix(meta.Path, ".jsonl") {
		t.Errorf("path %q should be a .jsonl file", meta.Path)
	}

	reopened, err := repo.Open(ctx, meta)
	if err != nil {
		t.Fatal(err)
	}
	if got := len(reopened.Entries(ctx, nil)); got != 1 {
		t.Errorf("entries = %d, want 1", got)
	}
}

func TestRepoListNewestFirst(t *testing.T) {
	ctx := context.Background()
	repo := NewJSONLRepo(t.TempDir())

	for _, id := range []string{"aaa", "bbb", "ccc"} {
		if _, err := repo.Create(ctx, CreateSessionOptions{Cwd: "/proj", ID: id}); err != nil {
			t.Fatal(err)
		}
	}
	// A session in a different project must not appear in a scoped listing.
	if _, err := repo.Create(ctx, CreateSessionOptions{Cwd: "/other", ID: "zzz"}); err != nil {
		t.Fatal(err)
	}

	scoped, err := repo.List(ctx, "/proj")
	if err != nil {
		t.Fatal(err)
	}
	if len(scoped) != 3 {
		t.Fatalf("scoped list = %d, want 3", len(scoped))
	}
	for i := 1; i < len(scoped); i++ {
		if scoped[i-1].CreatedAt < scoped[i].CreatedAt {
			t.Errorf("listing is not newest-first: %v", scoped)
		}
	}

	all, err := repo.List(ctx, "")
	if err != nil {
		t.Fatal(err)
	}
	if len(all) != 4 {
		t.Errorf("unscoped list = %d, want 4", len(all))
	}
}

func TestRepoListSkipsNonSessionFiles(t *testing.T) {
	ctx := context.Background()
	root := t.TempDir()
	repo := NewJSONLRepo(root)
	if _, err := repo.Create(ctx, CreateSessionOptions{Cwd: "/proj", ID: "good"}); err != nil {
		t.Fatal(err)
	}

	dir := filepath.Join(root, EncodeCwd("/proj"))
	// Junk that should be ignored rather than break the listing.
	if err := os.WriteFile(filepath.Join(dir, "notes.txt"), []byte("hi"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "broken.jsonl"), []byte("{not json\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	list, err := repo.List(ctx, "/proj")
	if err != nil {
		t.Fatalf("a malformed file should not break listing: %v", err)
	}
	if len(list) != 1 {
		t.Errorf("list = %d, want 1", len(list))
	}
}

func TestRepoListMissingRoot(t *testing.T) {
	ctx := context.Background()
	repo := NewJSONLRepo(filepath.Join(t.TempDir(), "does-not-exist"))
	list, err := repo.List(ctx, "")
	if err != nil {
		t.Fatalf("listing a missing root should be empty, not an error: %v", err)
	}
	if len(list) != 0 {
		t.Errorf("list = %d, want 0", len(list))
	}
}

func TestRepoDelete(t *testing.T) {
	ctx := context.Background()
	repo := NewJSONLRepo(t.TempDir())
	s, err := repo.Create(ctx, CreateSessionOptions{Cwd: "/proj"})
	if err != nil {
		t.Fatal(err)
	}
	meta, _ := s.Metadata(ctx)

	if err := repo.Delete(ctx, meta); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(meta.Path); !os.IsNotExist(err) {
		t.Error("session file should be gone")
	}
	// Deleting twice is not an error.
	if err := repo.Delete(ctx, meta); err != nil {
		t.Errorf("second delete: %v", err)
	}
}

// Forking copies entry lines verbatim, so a forked session is byte-identical
// to its source for the copied range.
func TestForkCopiesEntriesByteForByte(t *testing.T) {
	ctx := context.Background()
	root := t.TempDir()
	repo := NewJSONLRepo(root)

	src, err := repo.Create(ctx, CreateSessionOptions{Cwd: "/proj", ID: "src"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := src.AppendMessage(ctx, userMsg("one")); err != nil {
		t.Fatal(err)
	}
	if _, err := src.AppendMessage(ctx, assistantMsg("two", "anthropic", "m")); err != nil {
		t.Fatal(err)
	}
	if _, err := src.AppendMessage(ctx, userMsg("three")); err != nil {
		t.Fatal(err)
	}
	srcMeta, _ := src.Metadata(ctx)

	forked, err := repo.Fork(ctx, srcMeta, CreateSessionOptions{Cwd: "/proj", ID: "fork"}, ForkOptions{})
	if err != nil {
		t.Fatal(err)
	}
	forkMeta, _ := forked.Metadata(ctx)

	if forkMeta.ParentSessionPath != srcMeta.Path {
		t.Errorf("parentSession = %q, want %q", forkMeta.ParentSessionPath, srcMeta.Path)
	}

	srcLines := entryLines(t, srcMeta.Path)
	forkLines := entryLines(t, forkMeta.Path)
	if len(forkLines) != len(srcLines) {
		t.Fatalf("fork has %d entry lines, source has %d", len(forkLines), len(srcLines))
	}
	for i := range srcLines {
		if srcLines[i] != forkLines[i] {
			t.Errorf("entry line %d differs:\n src  %s\n fork %s", i, srcLines[i], forkLines[i])
		}
	}
}

// "before" is the /fork case: cut just ahead of a user message so it can be
// replayed differently.
func TestForkBeforeUserMessage(t *testing.T) {
	ctx := context.Background()
	repo := NewJSONLRepo(t.TempDir())
	src, err := repo.Create(ctx, CreateSessionOptions{Cwd: "/proj"})
	if err != nil {
		t.Fatal(err)
	}
	firstID, _ := src.AppendMessage(ctx, userMsg("one"))
	_, _ = src.AppendMessage(ctx, assistantMsg("two", "anthropic", "m"))
	thirdID, _ := src.AppendMessage(ctx, userMsg("three"))
	srcMeta, _ := src.Metadata(ctx)

	forked, err := repo.Fork(ctx, srcMeta, CreateSessionOptions{Cwd: "/proj"}, ForkOptions{EntryID: thirdID})
	if err != nil {
		t.Fatal(err)
	}
	entries := forked.Entries(ctx, nil)
	if len(entries) != 2 {
		t.Fatalf("forked entries = %d, want 2 (everything before the target)", len(entries))
	}
	if entries[0].Base().ID != firstID {
		t.Errorf("first entry = %s, want %s", entries[0].Base().ID, firstID)
	}
	for _, e := range entries {
		if e.Base().ID == thirdID {
			t.Error("the target user message must not be copied for position=before")
		}
	}
}

func TestForkAtIncludesTarget(t *testing.T) {
	ctx := context.Background()
	repo := NewJSONLRepo(t.TempDir())
	src, err := repo.Create(ctx, CreateSessionOptions{Cwd: "/proj"})
	if err != nil {
		t.Fatal(err)
	}
	_, _ = src.AppendMessage(ctx, userMsg("one"))
	secondID, _ := src.AppendMessage(ctx, assistantMsg("two", "anthropic", "m"))
	_, _ = src.AppendMessage(ctx, userMsg("three"))
	srcMeta, _ := src.Metadata(ctx)

	forked, err := repo.Fork(ctx, srcMeta, CreateSessionOptions{Cwd: "/proj"},
		ForkOptions{EntryID: secondID, Position: "at"})
	if err != nil {
		t.Fatal(err)
	}
	entries := forked.Entries(ctx, nil)
	if len(entries) != 2 {
		t.Fatalf("forked entries = %d, want 2", len(entries))
	}
	if entries[len(entries)-1].Base().ID != secondID {
		t.Errorf("last entry = %s, want the target %s", entries[len(entries)-1].Base().ID, secondID)
	}
}

func TestForkRejectsBadTarget(t *testing.T) {
	ctx := context.Background()
	repo := NewJSONLRepo(t.TempDir())
	src, err := repo.Create(ctx, CreateSessionOptions{Cwd: "/proj"})
	if err != nil {
		t.Fatal(err)
	}
	assistantID, _ := src.AppendMessage(ctx, assistantMsg("hi", "anthropic", "m"))
	srcMeta, _ := src.Metadata(ctx)

	_, err = repo.Fork(ctx, srcMeta, CreateSessionOptions{Cwd: "/proj"}, ForkOptions{EntryID: "missing1"})
	if !IsCode(err, CodeInvalidFork) {
		t.Errorf("missing entry: err = %v, want invalid_fork_target", err)
	}

	// position=before only makes sense ahead of a user message.
	_, err = repo.Fork(ctx, srcMeta, CreateSessionOptions{Cwd: "/proj"}, ForkOptions{EntryID: assistantID})
	if !IsCode(err, CodeInvalidFork) {
		t.Errorf("assistant target: err = %v, want invalid_fork_target", err)
	}
}

func TestForkInheritsSourceCwdAndMetadata(t *testing.T) {
	ctx := context.Background()
	repo := NewJSONLRepo(t.TempDir())
	src, err := repo.Create(ctx, CreateSessionOptions{
		Cwd:      "/proj",
		Metadata: map[string]any{"origin": "test"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := src.AppendMessage(ctx, userMsg("hi")); err != nil {
		t.Fatal(err)
	}
	srcMeta, _ := src.Metadata(ctx)

	forked, err := repo.Fork(ctx, srcMeta, CreateSessionOptions{}, ForkOptions{})
	if err != nil {
		t.Fatal(err)
	}
	forkMeta, _ := forked.Metadata(ctx)
	if forkMeta.Cwd != "/proj" {
		t.Errorf("cwd = %q, want inherited /proj", forkMeta.Cwd)
	}
	if forkMeta.Metadata["origin"] != "test" {
		t.Errorf("metadata = %v, want inherited", forkMeta.Metadata)
	}
}

// A forked session is independent: appending to it must not touch the source.
func TestForkIsIndependent(t *testing.T) {
	ctx := context.Background()
	repo := NewJSONLRepo(t.TempDir())
	src, err := repo.Create(ctx, CreateSessionOptions{Cwd: "/proj"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := src.AppendMessage(ctx, userMsg("shared")); err != nil {
		t.Fatal(err)
	}
	srcMeta, _ := src.Metadata(ctx)

	forked, err := repo.Fork(ctx, srcMeta, CreateSessionOptions{Cwd: "/proj"}, ForkOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := forked.AppendMessage(ctx, userMsg("only in fork")); err != nil {
		t.Fatal(err)
	}

	reopened, err := repo.Open(ctx, srcMeta)
	if err != nil {
		t.Fatal(err)
	}
	if got := len(reopened.Entries(ctx, nil)); got != 1 {
		t.Errorf("source entries = %d, want 1", got)
	}
}

func TestForkedEntriesKeepOriginalIDs(t *testing.T) {
	ctx := context.Background()
	repo := NewJSONLRepo(t.TempDir())
	src, err := repo.Create(ctx, CreateSessionOptions{Cwd: "/proj"})
	if err != nil {
		t.Fatal(err)
	}
	id, err := src.AppendMessage(ctx, userMsg("hi"))
	if err != nil {
		t.Fatal(err)
	}
	srcMeta, _ := src.Metadata(ctx)

	forked, err := repo.Fork(ctx, srcMeta, CreateSessionOptions{Cwd: "/proj"}, ForkOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := forked.Entry(ctx, id); !ok {
		t.Error("forked entries should keep their original ids so links stay intact")
	}
	leaf, _ := forked.LeafID(ctx)
	if leaf == nil || *leaf != id {
		t.Errorf("fork leaf = %v, want %s", leaf, id)
	}
}

// entryLines returns a session file's lines after the header.
func entryLines(t *testing.T, path string) []string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(strings.TrimRight(string(data), "\n"), "\n")
	if len(lines) <= 1 {
		return nil
	}
	return lines[1:]
}

var _ = ai.UserMessage{}
